version: '3.3'
volumes:
  pg_data:
  static:
  backend_static:
  backend_media:
  media:
services:
  db:
    image: postgres:13
    env_file: 
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    build: ../backend/
    env_file:
      - ./.env
    volumes:
      - backend_static:/app/backend_static
      - backend_media:/app/backend_media
    depends_on:
      - db
  frontend:
    build: ../frontend/
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
